### PR TITLE
add stock keyboard layout of Kinesis Advantage

### PR DESCRIPTION
**Pull request by jordiorlando**

### CODE REVIEW

**Comment by jordiorlando** [comment]
@alerque Could you split this into a separate kinesis-advantage.json file? Thanks for creating this!

**Comment by alerque** [comment]
I can, but rebasing this against your current master branch will just create a file conflict. You have two different things going on in 3feff0c. You make structural changes to the existing code base and add data files as part of the same commit. That makes it kind of tricky to sort out unless you rebase to split that up. Are you familiar with rebasing? Are you willing to do that on your master branch or should we work with the history we've got (if other people have forked it since you posted in the last 24 hours best not to touch it. If it's just you and me we can probably get away with doing whatever to it).

BTW I have updated Kinesis layout data with a few tweaks missing from what I posted earlier. I also have a version that is colored much the way the keyboard is (black). When I do add this do you want the colored or uncolored version in the layouts?

**Comment by jordiorlando** [comment]
I am not familiar with rebasing, but I am totally willing to do it. No one has yet forked my fork, so it should be fine. Any advice on what to do?

As for color, @iandoug and I have been talking on [Gitter](https://gitter.im/D1SC0tech/keyboard-layout-editor?utm_source=share-link&utm_medium=link&utm_campaign=share-link) about separating layouts from keycaps in the future, so I think uncolored would be best.

**Comment by alerque** [comment]
I started writing up instructions to do a quick rebase to fix my issue. My commit is easy, but it gets complicated quickly as the later merges you've done are also borked. You shouldn't just be merging branches on top of work that you've already implemented the same stuff! For example b2c158d is completely clobbered by 8b014c3. Is there anything in amj's code that you didn't want to pull across?

Also your commits are a bit of a wasteland. I'm sorry to be so harsh, but you should be aware that this makes it really hard for others to a) keep an eye on your progress and review the code or b) contribute. It might not matter for your own personal projects because you may never look at the history but it matters a lot when you get other people involved.

Stream of conciseness style commits at every moment of your work are a **good thing**. But they need to stay in your personal branches. If you are going to run the master branch of an open source project it's really helpful if you _don't_ put those commits on the master branch. Instead once you get each thing working you need to squash the commits into a single commit for each item. While you are working you may:
- commit: Work of function X
- commit: Bugfix in X
- commit: Work on function Y
- commit: Fix typo in X
- commit: Make X work
- commit: No really this time
- commit: reword Y

But before you send that up to github you should use rebase to squash that into two commits:
- commit: add function X [details]
- commit: add function Y [details]

So back to my question an the end of paragraph 1…

**Comment by jordiorlando** [comment]
Okay, it's good to know all of that. I'm teaching myself all of this as I go along, so I definitely have a lot to learn. I'd like to get this fixed, and then improve my habits from now on. There's no changing the past, but hopefully this can get sorted out.

As far as I know, there is nothing in amj's fork that we don't want.

**Comment by jordiorlando** [comment]
As for the commit workflow, how does one split two changes in one file into two different commits? E.g. if I were to write functions x and y in foo.bar on my personal branch, how would I commit them separately?

**Comment by alerque** [comment]
> There's no changing the past

Actually there is. That's the thing with git. You actually _can_ rewrite history. And that's a great way to learn.

I don't have a ton of time today but maybe the best way to use the time I have is to show you how this might look. I won't be able to clean up the whole thing but I'll run through how I would start of in in a screencast. Upload to come...

**Comment by jordiorlando** [comment]
Wow, fantastic! Thank you so much for your help!

**Comment by iandoug** [comment]
I suppose I should jump in here, I also borrowed your Kinesys layout and put it in a separate file.. I'm also on a steep learning curve with Git... still a Big Black Box to me, and not always sure of the impact of what I do. I assumed my branch was not going to mess with anyone else's, but perhaps I was wrong.

**Comment by alerque** [comment]
@iandoug No worries man. The video(s) I'm preparing will probably go over your head because I actualaly mention your branch with a big question mark because I didn't know if you were ever the same person as one of the other faces in this branch mess or what. In any event what you do in your branches won't affect anybody else, but if you want to benefit from the other changes in those branches we'll have to rebase your commits onto the fork—but wait for the dust to settle to worry about that!

@D1SC0tech Videos are done but my upload is really slow today so it will be a while before I can drop links here.

**Comment by iandoug** [comment]
I'm using KDevelop (which is also new to me, I normally just live in Kate) and it's supposed to have full git support but I couldn't quite fathom the user interface. On my first commit I thought it was going to let me write comments for each file, but it didn't, hence the long rant in the 'overview'. I also discovered the Update command does the opposite of what I wanted and disappeared some changes. It also would not push things up, and I could not find where to set my username/pass, so eventually hit Google and dropped back to the command line to try to get things sorted. I've only been doing this since last night so complete newbie and probably Screwing Up all over... apologies. I also lifted your Kinesys code from the patch file, didn't know any other way.  Apparently there is no way to add comments in a json file, otherwise I would have listed the source. For the other layouts I found, I named them after the handle of the author as best I could. I managed to lose track of two of the authors (hence Unknown 1 and 2). Google can't find the original links with the hash string.

Need to go out now, not sure when I will be back.

**Comment by iandoug** [comment]
Forgot to mention that just 2 days ago I was wishing someone HAD done the Kinesys (and Maltron) layout, and then the Internet delivers, like it often does... :-)

**Comment by alerque** [comment]
@D1SC0tech  [Three videos](https://www.youtube.com/playlist?list=PLBr0-mWMB6wQcy5B5d9BUFd5vz1BFFOx-) that run through some things that could be done with this commit history are up at:
- http://youtu.be/FyTWk_nVzbU
- http://youtu.be/-8nsu8k2lbU
- http://youtu.be/wszWM-coJ5Y

Keep in mind that I didn't check out whether actually worked code wise but just showed the general steps that _could_ be taken. You'll need to run through the process going a touch slower and keeping an eye on what you want to happen with each series of commits for this to be useful. A copy of the branch I worked on for this demo [is available in my fork](https://github.com/alerque/keyboard-layout-editor/commits/d1sc0tech-rebase-walkthrough). Note especially how it saved the attribution for commits. Because I mashed them around they all have my name on them as committer, but it attributes the author to you or whoever originated the material.

**Comment by iandoug** [comment]
Thanks, have started with the first one but Internet really sucks today (presume it's the usual end-of-month problem of users with spare bandwidth tyring to use up bandwidth that the ISPs are short of ...) so will have to try again later.

**Comment by jordiorlando** [comment]
@alerque I'm currently working through your videos, they're super helpful. I'll let you know as soon as it's fixed.

**Comment by iandoug** [comment]
@alerque did you do something different with the second episode? My bandwidth is sucking so badly the last 3 days that I downloaded the videos with flashgot (because playback on Youtube was unwatchable), the first and third work fine but the second has missing audio (even tho it works on Youtube). I tried  HD mp4, HD webm and large MP4. I remember a few months back I had a similar problem with a video on Youtube, I eventually ended up having to download a separate mp3 audio track, then merge with VLC or somesuch. So before I go that route I was just wondering if I was doing something stupid ...

**Comment by iandoug** [comment]
Sorted... grabbed the audio, fed the audio and video thru ffmpeg and got working file.
Thanks :-)

**Comment by iandoug** [comment]
@alerque: thanks so much for taking the time and trouble to make these videos. I will need to learn a lot more about git before I will feel comfortable trying some of what you did. I guess now that ijprest has surfaced, we should rebase off his version, and update that, rather than running separate forks, assuming he is open to that.

**Pull request closed without merging**
